Ball
float Ball::_startVelocityX
Referenced by resetVelocity.
float Ball::_startVelocityY
Referenced by resetVelocity.
float Ball::_velocityX
Referenced by resetVelocity, updatePosition.
float Ball::_velocityY
Referenced by resetVelocity, updatePosition.
float Ball::_acceleration
Referenced by updatePosition.
bool Ball::_hasBounced
Referenced by hasBounced, updatePosition.
Ball::Ball(unsigned short int &windowLimitX, unsigned short int &windowLimitY, unsigned short int &wallThickness, float movingSpeedX, float movingSpeedY)
void Ball::updatePosition(float &deltaTime, unsigned short int &wallThickness, float &paddlePositionY, unsigned short int &paddleLength)
References _acceleration, _hasBounced, PongObject::_position, _velocityX, _velocityY, PongObject::_windowLimitX, PongObject::_windowLimitY, XYPosition::x, XYPosition::y.
Referenced by Game::UpdateGame.
bool * Ball::hasBounced()
References _hasBounced.
Referenced by Game::UpdateGame.
bool Ball::ballOut()
References PongObject::_position, PongObject::_windowLimitX, PongObject::_windowLimitY, XYPosition::x, XYPosition::y.
Referenced by Game::UpdateGame.
void Ball::resetVelocity()
References _startVelocityX, _startVelocityY, _velocityX, _velocityY.
Referenced by Game::UpdateGame.