PongObject
unsigned short int PongObject::_windowLimitX
Referenced by Ball::ballOut, setWindowLimits, Ball::updatePosition.
unsigned short int PongObject::_windowLimitY
Referenced by Ball::ballOut, Paddle::changePaddlePosition, Paddle::Paddle, setWindowLimits, Ball::updatePosition.
XYPosition PongObject::_position
Referenced by Ball::ballOut, Paddle::changePaddlePosition, getPosition, Paddle::Paddle, setPosition, updateDrawingObject, Ball::updatePosition.
unsigned short int PongObject::_length
Referenced by Paddle::changePaddlePosition, getLength, Paddle::Paddle, updateDrawingObject.
unsigned short int PongObject::_thickness
Referenced by getThickness, Paddle::Paddle, updateDrawingObject.
std::vector<unsigned short int> PongObject::_color
Referenced by getColor, switchColor.
SDL_Rect PongObject::_drawingObject
Referenced by getDrawingObject, updateDrawingObject.
PongObject::PongObject(unsigned short int &windowLimitX, unsigned short int &windowLimitY, unsigned short int &wallThickness)
PongObject::~PongObject()
void PongObject::updateDrawingObject()
References _drawingObject, _length, _position, _thickness, XYPosition::x, XYPosition::y.
Referenced by Game::UpdateGame.
void PongObject::switchColor()
References _color.
Referenced by Game::GenerateOutput.
XYPosition * PongObject::getPosition()
References _position.
Referenced by Game::UpdateGame.
SDL_Rect * PongObject::getDrawingObject()
References _drawingObject.
Referenced by Game::GenerateOutput.
std::vector< unsigned short int > PongObject::getColor()
References _color.
Referenced by Game::GenerateOutput.
unsigned short int * PongObject::getLength()
References _length.
Referenced by Game::UpdateGame.
unsigned short int * PongObject::getThickness()
References _thickness.
void PongObject::setPosition(float x, float y)
References _position, XYPosition::x, XYPosition::y.
Referenced by Game::UpdateGame.
void PongObject::setWindowLimits(unsigned short int, unsigned short int)
References _windowLimitX, _windowLimitY.