Game
bool Game::mIsRunning
Referenced by GameLoop, ProcessInput.
SDL_Window* Game::mWindow
Referenced by Initialize, ShutDownGame.
SDL_Renderer* Game::mRenderer
Referenced by GenerateOutput, Initialize, ShutDownGame.
unsigned short int Game::_windowSizeX
Referenced by GenerateOutput, Initialize, UpdateGame.
unsigned short int Game::_windowSizeY
Referenced by GenerateOutput, Initialize, UpdateGame.
bool Game::_isRightWall
Referenced by GenerateOutput.
unsigned short int Game::_wallThickness
Referenced by getWallThickness, UpdateGame.
long int Game::_score
Referenced by UpdateGame.
bool Game::_colorSwap
Referenced by GenerateOutput, UpdateGame.
const Uint8* Game::state
Referenced by ProcessInput, UpdateGame.
Uint32 Game::mTicksCount
Referenced by UpdateGame.
std::shared_ptr<Ball> Game::ball1
Referenced by GenerateOutput, UpdateGame.
std::shared_ptr<Paddle> Game::paddle1
Referenced by GenerateOutput, UpdateGame.
Game::Game(unsigned short int windowSizeX, unsigned short int windowSizeY, unsigned short int paddleSize, bool isRightWall)
bool Game::Initialize()
References _windowSizeX, _windowSizeY, mRenderer, mWindow.
Referenced by main.
void Game::GameLoop()
References GenerateOutput, mIsRunning, ProcessInput, UpdateGame.
Referenced by main.
void Game::ShutDownGame()
References mRenderer, mWindow.
Referenced by main.
void Game::ProcessInput()
References mIsRunning, state.
Referenced by GameLoop.
void Game::UpdateGame()
References _colorSwap, _score, _wallThickness, _windowSizeX, _windowSizeY, ball1, Ball::ballOut, Paddle::changePaddlePosition, PongObject::getLength, PongObject::getPosition, Ball::hasBounced, mTicksCount, paddle1, Ball::resetVelocity, PongObject::setPosition, state, PongObject::updateDrawingObject, Ball::updatePosition, XYPosition::y.
Referenced by GameLoop.
void Game::GenerateOutput()
References _colorSwap, _isRightWall, _windowSizeX, _windowSizeY, ball1, PongObject::getColor, PongObject::getDrawingObject, mRenderer, paddle1, PongObject::switchColor.
Referenced by GameLoop.
unsigned short int * Game::getWallThickness()
References _wallThickness.